import { Inter } from 'next/font/google';
import '@/style/globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Printhis Kiosk 1',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body
				className={
					inter.className +
					'min-w-screen min-h-screen bg-gradient-to-tl from-sky-100 via-sky-200 to-sky-300 bg-no-repeat'
				}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
