import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Printhis Kiosk 1',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body
				className={
					inter.className +
					'min-w-[1080] min-h-[1920] bg-gradient-to-tl from-sky-100 via-sky-200 to-sky-300'
				}>
				{children}
			</body>
		</html>
	);
}
